default: &default
  adapter: postgresql
  encoding: unicode
  username: dev
  password: dev
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: elcheck_development

test:
  <<: *default
  database: elcheck_test
production:
  <<: *default
  database: elcheck_production
  username: Checker
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
